### ISSUE TITLE
Evil-mode is not deprecated and this line is wildly out of tune with emacs

### ISSUE THREAD

**Issue by hammerandtongs** [erikw/vim-keybindings-everywhere-the-ultimate-list#10]
> [evil-mode](https://www.emacswiki.org/emacs/Evil) Deprecated, check out Vimpulse or Vim Mode.

That isn't even vaguely correct. Just link to evil-mode and be done if you aren't familiar with the emacs ecosystem.

Evil-mode is far more capable then viper+vimpulse and vim-mode (both of which are ancient and unmaintained).

I don't think its actually arguable and its certainly not what the broad community would say.

**Comment by erikw** [comment]
Thank you @hammerandtongs highlighting this issue! Feel free to make a PR correcting it :)

**Comment by c02y** [comment]
According the emacswiki page of [Evil-mode](https://www.emacswiki.org/emacs/Evil),

> Evil is the successor to the now-obsolete Vimpulse and vim-mode.

So

  * :heavy_plus_sign: ~~[Vimpulse](https://www.emacswiki.org/emacs/Vimpulse)~~ Deprecated, check out Evil.
  * :heavy_plus_sign: ~~[Vim Mode](https://www.emacswiki.org/emacs/VimMode)~~ Deprecated, check out Evil.
  * :heavy_plus_sign: [evil-mode](https://www.emacswiki.org/emacs/Evil)
