### ISSUE TITLE
Xcode is not accurate, it has built in support

### ISSUE THREAD

**Issue by kylepeeler** [erikw/vim-keybindings-everywhere-the-ultimate-list#15]
You mention to use XVim for Xcode, which itself is deprecated, replaced by XVim 2, [which broke on XCode 14](https://github.com/XVimProject/XVim2). There is however built in support for a subset of Vim commands as of the latest version of XCode.

**Comment by erikw** [comment]
I believe you are correct. The PR #22 should have addressed this. Thanks for reporting!
