### ISSUE TITLE
onivim is no longer maintained

### ISSUE THREAD

**Issue by 2gn** [erikw/vim-keybindings-everywhere-the-ultimate-list#29]
There's been no commit since the last one by the original author @bryphe, in 2021. It should be removed from this list temporary and maybe revive it hopefully when the development starts again.

https://github.com/onivim/oni2

**Comment by erikw** [comment]
I believe you are right: https://github.com/onivim/oni2/issues/3861

I'll mark it as deprecated. Thanks for reporting!
