### ISSUE TITLE
Is this a mistype?

### ISSUE THREAD

**Issue by brainwo** [erikw/vim-keybindings-everywhere-the-ultimate-list#64]
Reading through the shell section I find this abnormality:
```md
* :white_check_mark: [tcsh](https://www.tcsh.org/) - Put this in your ksh startup file e.g. `~/.kshrc` ([reference](https://www.oreilly.com/library/view/mac-os-x/0596004583/ch04s02.html)):
```

Looks like it supposed to say `tcsh` there, instead of `ksh`.
I'm not a `tcsh` user so I don't know if `tcsh` and `ksh` is related to each other.

**Comment by erikw** [comment]
Hello, and thank you for reporting. 

I’m unable to investigate at the moment how general this setting is. However it seems safer to say ‘tcsh’ as you say. 

Please open a PR ☺️
