### ISSUE TITLE
kindaVim YO!

### ISSUE THREAD

**Issue by godbout** [erikw/vim-keybindings-everywhere-the-ultimate-list#70]
i just saw my app in here lol

but it's described as "[kindaVim](https://kindavim.app/) - Get vim-like navigation in any macOS text field.". kV adds Vim motions in text fields/areas AND in UI. like you go have fun in dropdowns, lists, menus with `j`, `k`, `gg`, `G`, etc. etc. not just in text fields!

PR possible?

**Comment by erikw** [comment]
Yes PR is appreciated if you have a suggestion or fix :)

**Comment by godbout** [comment]
done here: https://github.com/erikw/vim-keybindings-everywhere-the-ultimate-list/pull/71

**Comment by godbout** [comment]
but two other things:

1. there's also ShadowVim, that adds a neovim engine to Xcode: https://github.com/mickael-menu/ShadowVim
2. when i was editing kV's description i saw there was [Homerow just above](https://github.com/mickael-menu/ShadowVim)!!! are you considering Homerow related to Vim? coz kV is actually a part of three apps, one being [Wooshy](https://wooshy.app), that is actually like Homerow (Wooshy came out first), and [Scrolla](https://scrolla.app). so i'm wondering if we should add them to your list? there's some links to Vim in the sense that with Scrolla you use Vim motions to scroll, and Wooshy you can use some Vim motions to choose where to click anywhere on macOS. but that's the only link they have with Vim, so i'm wondering 🤔️
